--- #for Current running environment
spring:
  profiles:
    active: dev
  jakson:
    timeZone: Asia/Kolkata

--- #for dev profile configuration.
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: khataBill-dev
      auto-index-creation: true
    web:
      pagable:
        default-pagesize: 20
        max-page-size: 1000
    servlet:
      multipart:
        enable: true
        max-request-size: 10Mb
        max-file-size: 20Mb
    security:
      basic:
        enable: false
  http:
    log-request-details:
      debug: true

server:
  compression:
    enabled: true
  port: 7200


--- #for UAT profile configuration.
spring:
  profiles: test
  data:
    mongodb:
      host: localhost
      port: 27017
      database: khataBill-test
      auto-index-creation: true
    web:
      pagable:
        default-pagesize: 20
        max-page-size: 1000
    servlet:
      multipart:
        enable: true
        max-request-size: 10Mb
        max-file-size: 20Mb
    security:
      basic:
        enable: false
debug: true

server:
  compression:
    enabled: true
  port: 7200

--- #for dev profile configuration.
spring:
  profiles: prod
  data:
    mongodb:
      host: localhost
      port: 27017
      database: khataBill-dev
      auto-index-creation: true
    web:
      pagable:
        default-pagesize: 20
        max-page-size: 1000
    servlet:
      multipart:
        enable: true
        max-request-size: 10Mb
        max-file-size: 20Mb
    security:
      basic:
        enable: false
debug: true

server:
  compression:
    enabled: true
  port: 7200






